/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

//import static analizadores.AnalisadorLexico.listaSaidas;
import static analizadores.AnalisadorSintatico.listaErros;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import tokens.LexicalError;
import tokens.Out;

/**
 *
 * @author Dell-User
 */
public class JPanelComplet extends javax.swing.JPanel {

    /**
     * Creates new form JPanelComplet
     */
    public JPanelComplet() {
        initComponents();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultadoFinal = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        txtResultadoFinal.setBackground(new java.awt.Color(255, 255, 255));
        txtResultadoFinal.setColumns(20);
        txtResultadoFinal.setForeground(new java.awt.Color(0, 0, 0));
        txtResultadoFinal.setRows(5);
        jScrollPane2.setViewportView(txtResultadoFinal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea txtResultadoFinal;
    // End of variables declaration//GEN-END:variables
}
