/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import analizadores.AnalisadorLexico;
import static analizadores.AnalisadorLexico.i;
import static analizadores.AnalisadorLexico.preencherArrayPalavrasReservadas;
import analizadores.AnalisadorSintatico;
import static analizadores.AnalisadorSintatico.count;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import javax.swing.JOptionPane;
import tokens.Out;
//import static views.JPanelAnalex.carregarTabelaAnalex;
import static views.JPanelComplet.txtResultadoFinal;

/**
 *
 * @author Dell-User
 */
public class Main extends javax.swing.JFrame {

    public static String aux;

    //Localização
    public static int xx = 0;
    public static int yy = 0;

    //Gread para adaptacao dos JPanelForms
    public static GridBagLayout layout = new GridBagLayout();

    //Instanciado os JPanels
    public static JPanelAnalex analex;
    public static JPanelComplet compiler;
    public static JPanelsHome home;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        //Deixar o Panel e o formulario transparentes
        this.setBackground(new Color(0, 0, 0, 0));
        jPanel1.setBackground(new Color(0, 0, 0, 0));

        //Palavras resevadas
        preencherArrayPalavrasReservadas();

        //Termino de Instatncia
        analex = new JPanelAnalex();
        compiler = new JPanelComplet();
        home = new JPanelsHome();

        //Definindo o layout ao JPanel que servira de Base aos outros
        jPanel2.setLayout(layout);

        //Variavel que vai enquadras os JPanels no Panel ase
        GridBagConstraints redimensionar = new GridBagConstraints();

        //Redimensionar
        redimensionar.gridx = 0;
        redimensionar.gridy = 0;
        jPanel2.add(compiler, redimensionar);
        redimensionar.gridx = 0;
        redimensionar.gridy = 0;
        jPanel2.add(analex, redimensionar);
        redimensionar.gridx = 0;
        redimensionar.gridy = 0;
        jPanel2.add(home, redimensionar);

        //Tornar todos invisiveis
        visibilidade();

        //Tornar a Home Page visisvel
        home.setVisible(true);

    }

    public static void visibilidade() {
        analex.setVisible(false);
        compiler.setVisible(false);
    }

    //Escrever no ficheiro
    public static void write(String path, String conteudo) {
        try {
            BufferedWriter buffwrite = new BufferedWriter(new FileWriter(path));
            buffwrite.append(conteudo);
            buffwrite.close();
        } catch (IOException e) {
        }

    }

    //Limpar dados do ficheiro
    public static void limparFicheiro() {
        try {
            Writer out = new FileWriter("main.c");
            out.write("");
            out.flush();
            out.close();
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCloser3 = new javax.swing.JButton();
        jLabelDragForm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSource = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnAnalex = new javax.swing.JButton();
        btnExecute = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCloser3.setBorder(null);
        btnCloser3.setContentAreaFilled(false);
        btnCloser3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCloser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloser3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCloser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 40, 40));

        jLabelDragForm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelDragFormMouseDragged(evt);
            }
        });
        jLabelDragForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelDragFormMousePressed(evt);
            }
        });
        jPanel1.add(jLabelDragForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 40));

        txtSource.setColumns(20);
        txtSource.setRows(5);
        jScrollPane1.setViewportView(txtSource);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 970, 360));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 970, 100));

        btnAnalex.setBorder(null);
        btnAnalex.setContentAreaFilled(false);
        btnAnalex.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAnalex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalexActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnalex, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 90, 30));

        btnExecute.setBorder(null);
        btnExecute.setContentAreaFilled(false);
        btnExecute.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });
        jPanel1.add(btnExecute, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 50, 80, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewsbackground/Main_Form.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1021, 592));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelDragFormMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDragFormMouseDragged
        // TODO add your handling code here:
        //Posição do mouse na tela
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //Definir a localização do formulario
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jLabelDragFormMouseDragged

    private void jLabelDragFormMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDragFormMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jLabelDragFormMousePressed

    private void btnCloser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloser3ActionPerformed
        // TODO add your handling code here:
        int returnValue = 0;
        returnValue = JOptionPane.showConfirmDialog(null, "Pretende realmente Encerrar a Aplicação?", "Encerrar", JOptionPane.YES_NO_OPTION);
        if (returnValue == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Muito obrigado! Volte sempre. :´) ");
            System.exit(0);
        } else if (returnValue == JOptionPane.NO_OPTION) {
        }
    }//GEN-LAST:event_btnCloser3ActionPerformed

    private void btnAnalexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalexActionPerformed
        // TODO add your handling code here:
        try {
            visibilidade();
            analex.setVisible(true);
            //Apagar conteudo do ficheiro auxiliar
            limparFicheiro();
            //Escrever o ficheiro auxiliar
            write("main.c", txtSource.getText());

            AnalisadorLexico sc = new AnalisadorLexico("./main.c");
            Out token = new Out();
            do {
                token = sc.nextToken();

            } while (token != null);
            i = 0;
            //carregarTabelaAnalex();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAnalexActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        // TODO add your handling code here:
        visibilidade();
        compiler.setVisible(true);
        count = 0;
        try {
            if (txtSource.getText() == null) {
                JOptionPane.showMessageDialog(null, "Preencha a area do codigo!");
            } else {
                aux = "";
            }
            AnalisadorLexico sc = new AnalisadorLexico("./input.txt");
            AnalisadorSintatico anaS = new AnalisadorSintatico(sc);
        } catch (Exception e) {
        }
        txtResultadoFinal.setText(aux);
    }//GEN-LAST:event_btnExecuteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalex;
    private javax.swing.JButton btnCloser3;
    private javax.swing.JButton btnExecute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDragForm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea txtSource;
    // End of variables declaration//GEN-END:variables
}
