/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokens;

/**
 *
 * @author Dell-User
 */
public enum Token {
    TOKEN_INT, TOKEN_FLOAT, TOKEN_DOUBLE,
    TOKEN_ID, TOKEN_ABRE_PARENTESES, TOKEN_FECHA_PARENTESES,
    TOKEN_ABRE_PARENTESES_RECTOS, TOKEN_FECHA_PARENTESES_RECTOS,
    TOKEN_ABRE_PARENTESES_CURVOS, TOKEN_FECHA_PARENTESES_CURVOS,
    TOKEN_PONTO_E_VIRGULA, TOKEN_VIRGULA, TOKEN_PONTO, TOKEN_IGUAL,
    TOKEN_DIFERENTE, TOKEN_E_COMERCIAL, TOKEN_MENOS, TOKEN_MAIS,
    TOKEN_MAIOR_IGUAL, TOKEN_MENOR_IGUAL, TOKEN_MENOR_MENOR_IGULA,
    TOKEN_ABRE_CHAVETAS, TOKEN_FECHA_CHAVETAS, TOKEN_BARRA, TOKEN_OU,
    TOKEN_PERCENTAGEM, TOKEN_CIRCUNFLEXO, TOKEN_TIL, TOKEN_DIVISAO, TOKEN_ASTERISCO,
    TOKEN_PLICAS, TOKEN_ASPAS, TOKEN_COMPACTO_DIVISAO_IGUAL,TOKEN_CHAR, TOKEN_CONTINUE, 
    TOKEN_SWITCH, TOKEN_CASE, TOKEN_BREAK, TOKEN_WHILE, TOKEN_LONG, TOKEN_VOID, TOKEN_RETURN,
    TOKEN_FOR, TOKEN_STDIO_H, TOKEN_STDLIB_H, TOKEN__BOOL, TOKEN_STRUCT,
    TOKEN_TYPEDEF, TOKEN_IF, TOKEN_DO,TOKEN_DIGITO,TOKEN_PALAVRA, TOKEN_NEGACAO, 
    TOKEN_CHAPEU_COMPACTO, TOKEN_CHAPEU, TOKEN_CARACTER, TOKEN_IGUAL_LOGICO, 
    TOKEN_ASTERISCO_IGUAL, TOKEN_MENOS_IGUAL, TOKEN_DECREMENTAL, 
    TOKEN_MENOS_MAIOR, TOKEN_PERCENTAGEM_IGUAL, TTOKEN_E_COMERCIAL_LOGICO, 
    TOKEN_E_COMERCIAL_COMPACTO, TOKEN_BARRA_COMPACTO, TOKEN_E_COMERCIAL_LOGICO,
    TOKEN_MAIS_COMPACTO, TOKEN_INCREMENTO, TOKEN_MENOR_MENOR, TOKEN_MENOR, 
    TOKEN_MAIOR, TOKEN_MAIOR_MAIOR_IGUAL, TOKEN_MAIOR_MAIOR, TOKEN_INCLUDE,
    TOKEN_DEFINE, TOKEN_DIGITO_INT, TOKEN_DIGITO_FLOAT, TOKEN_ELSE, TOKEN_STRING, TOKEN_EOF
}
